version: "3.6"
services:
  mongo:
    image: mongo
    container_name: mongo_compose
    volumes:
      - "./volumes/mongodb/data/configdb:/data/configdb"
      - "./volumes/mongodb/data/db:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"

  redis:
    image: redis:4-alpine
    container_name: redis_compose
    volumes:
      - "./volumes/redis/data:/data"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    container_name: nginx_compose
    volumes:
      - "./volumes/nginx/etc/nginx:/etc/nginx"
    ports:
      - "8080:80"